name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI/CD Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: pull docker image
      run: sudo docker pull mhamzakhan295/cicd-pipeline:latest
      
    - name: Run docker container
      run: sudo docker run -d -p 8080:8080 mhamzakhan295/cicd-pipeline:latest
      
      
    
