name: CI/CD Pipeline

on:
  push:
    branches: 
          - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Login Dockerhub
      uses: docker/login-action@v1
      with:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      
    - name: Build the Docker image
      run: docker build -t cicd-pipeline:latest .
    - name: Push to Dockerhub
      run: docker push mhamzakhan295/cicd-pipeline:latest
